### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

### ISSUE THREAD

**Issue by chowkamlee81** [ZQPei/deep_sort_pytorch#101]
Tried to execute 

python deep/train.py .

Code got crashed at https://github.com/ZQPei/deep_sort_pytorch/blob/master/deep_sort/deep/model.py#L82
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "/snap/pycharm-community/179/plugins/python-ce/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/179/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sdk/Analysis/centerNet-deep-sort-master/deep/train.py", line 194, in <module>
    main()
  File "/home/sdk/Analysis/centerNet-deep-sort-master/deep/train.py", line 186, in main
    train_loss, train_err = train(epoch)
  File "/home/sdk/Analysis/centerNet-deep-sort-master/deep/train.py", line 89, in train
    outputs = net(inputs)
  File "/home/sdk/anaconda3/envs/reinforce_learn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "./model.py", line 84, in forward
    x = self.conv(x)
  File "/home/sdk/anaconda3/envs/reinforce_learn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdk/anaconda3/envs/reinforce_learn/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/sdk/anaconda3/envs/reinforce_learn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdk/anaconda3/envs/reinforce_learn/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405

**Comment by ZQPei** [comment]
Error occured at these lines `outputs = net(inputs)` and `x = self.conv(x)`.
Seems that your inputs is incorrect.

**Comment by chowkamlee81** [comment]
x=torch.randn(4,3,128,64, dtype=torch.float, device=device)

**Comment by chowkamlee81** [comment]
Problem with conda pytorch version...
