### ISSUE TITLE
moov atom not found

### ISSUE THREAD

**Issue by santhoskumarayyappan** [ZQPei/deep_sort_pytorch#106]
I followed all steps in the quick start , but i get this following error.
"Loading weights from ./detector/YOLOv3/weight/yolov3.weights... Done!
Loading weights from ./deep_sort/deep/checkpoint/ckpt.t7... Done!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff19000] moov atom not found
VIDIOC_REQBUFS: Function not implemented
Traceback (most recent call last):
  File "yolov3_deepsort.py", line 125, in <module>
    with VideoTracker(cfg, args) as vdo_trk:
  File "yolov3_deepsort.py", line 49, in __enter__
    assert self.vdo.isOpened()
AssertionError"
please help to solve this error.

**Comment by edgexspear** [comment]
try another video？
