### ISSUE TITLE
AttributeError: 'YamlParser' object has no attribute 'YOLOV3'

### ISSUE THREAD

**Issue by tosonw** [ZQPei/deep_sort_pytorch#150]
你好，我这运行yolov3_deepsort.py时保错：
Traceback (most recent call last):
  File "/e/myl/tracker/deep_sort_pytorch_ZQPei/yolov3_deepsort.py", line 158, in <module>
    with VideoTracker(cfg, args, video_path=args.VIDEO_PATH) as vdo_trk:
  File "/e/myl/tracker/deep_sort_pytorch_ZQPei/yolov3_deepsort.py", line 37, in __init__
    self.detector = build_detector(cfg, use_cuda=use_cuda)
  File "/e/myl/tracker/deep_sort_pytorch_ZQPei/detector/__init__.py", line 8, in build_detector
    return YOLOv3(cfg.YOLOV3.CFG, cfg.YOLOV3.WEIGHT, cfg.YOLOV3.CLASS_NAMES,
AttributeError: 'YamlParser' object has no attribute 'YOLOV3'

我debug进去看到导入的数据都是正常的，里面有YOLOV3，请问这是什么问题？？
随后我修改：
    cfg = get_config()
    cfg.merge_from_file(args.config_detection)
    cfg.merge_from_file(args.config_deepsort)
将args.config_detection放入get_config中，然后又会报错AttributeError: 'YamlParser' object has no attribute 'DEEPSORT'，请问这里需要怎么修改？？我实在修改不正确了

**Comment by ZQPei** [comment]
请问你修改过代码么？如果没有修改过的话，应该不会出问题才对

**Comment by edgexspear** [comment]
> 你好，我这运行yolov3_deepsort.py时保错：
> Traceback (most recent call last):
> File "/e/myl/tracker/deep_sort_pytorch_ZQPei/yolov3_deepsort.py", line 158, in
> with VideoTracker(cfg, args, video_path=args.VIDEO_PATH) as vdo_trk:
> File "/e/myl/tracker/deep_sort_pytorch_ZQPei/yolov3_deepsort.py", line 37, in **init**
> self.detector = build_detector(cfg, use_cuda=use_cuda)
> File "/e/myl/tracker/deep_sort_pytorch_ZQPei/detector/**init**.py", line 8, in build_detector
> return YOLOv3(cfg.YOLOV3.CFG, cfg.YOLOV3.WEIGHT, cfg.YOLOV3.CLASS_NAMES,
> AttributeError: 'YamlParser' object has no attribute 'YOLOV3'
> 
> 我debug进去看到导入的数据都是正常的，里面有YOLOV3，请问这是什么问题？？
> 随后我修改：
> cfg = get_config()
> cfg.merge_from_file(args.config_detection)
> cfg.merge_from_file(args.config_deepsort)
> 将args.config_detection放入get_config中，然后又会报错AttributeError: 'YamlParser' object has no attribute 'DEEPSORT'，请问这里需要怎么修改？？我实在修改不正确了

我也遇到了同样的问题了，你解决了吗？

**Comment by edgexspear** [comment]
解决方法  pip install --upgrade  easydict

**Comment by li-wenzhan** [comment]
> 解决方法 pip install --upgrade easydict

It still cannot work :-(

**Comment by li-wenzhan** [comment]
> 解决方法 pip install --upgrade easy
尝试过了，仍然报错...

**Comment by fushiwen1** [comment]
请问如果还是在报错怎么办
