### ISSUE TITLE
RuntimeError: output with shape [1, 128, 64] doesn't match the broadcast shape [3, 128, 64]

### ISSUE THREAD

**Issue by lsuperman** [ZQPei/deep_sort_pytorch#153]
I tried to run deep_sort/deep/feature_extractor.py, but there was a problem.

Traceback (most recent call last):
  File "D:/目标检测各模型/deep_sort_pytorch-master/deep_sort/deep/feature_extractor.py", line 56, in <module>
    feature = extr(img)
  File "D:/目标检测各模型/deep_sort_pytorch-master/deep_sort/deep/feature_extractor.py", line 44, in __call__
    im_batch = self._preprocess(im_crops)
  File "D:/目标检测各模型/deep_sort_pytorch-master/deep_sort/deep/feature_extractor.py", line 39, in _preprocess
    im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(0) for im in im_crops], dim=0).float()
  File "D:/目标检测各模型/deep_sort_pytorch-master/deep_sort/deep/feature_extractor.py", line 39, in <listcomp>
    im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(0) for im in im_crops], dim=0).float()
  File "F:\softmanage\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "F:\softmanage\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "F:\softmanage\Anaconda3\lib\site-packages\torchvision\transforms\functional.py", line 208, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 128, 64] doesn't match the broadcast shape [3, 128, 64]
can you help me ? thanks!!!

**Comment by Zsugabubus27** [comment]
Hi!

It is because the Extractor expects list of images, however it is called with a single image
Change this:
`feature = extr(img)`
to this:
`feature = extr([img])`

Note that this does not affects the behaviour of the whole algorithm since running feature_extractor.py only is just for testing.
