### ISSUE TITLE
重新训练Re-ID模型

### ISSUE THREAD

**Issue by chengzilizhi** [ZQPei/deep_sort_pytorch#16]
你好，我在尝试重新训练Re-ID模型，将Market-1501数据集放置于data/train下运行train.py报错。

Traceback (most recent call last):
  File "train.py", line 43, in <module>
    torchvision.datasets.ImageFolder(train_dir, transform=transform_train),
  File "/home/mxc-lab-ubuntu/anaconda3/envs/pytorch_041/lib/python3.5/site-packages/torchvision/datasets/folder.py", line 209, in __init__
    target_transform=target_transform)
  File "/home/mxc-lab-ubuntu/anaconda3/envs/pytorch_041/lib/python3.5/site-packages/torchvision/datasets/folder.py", line 87, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: data/train
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,webp

**Comment by ZQPei** [comment]
你需要重新组织Market1501数据集。把不同的人放在不同的文件夹下。
