### ISSUE TITLE
run error from yolov3_deepsort_eval.py

### ISSUE THREAD

**Issue by Leizhengwang** [ZQPei/deep_sort_pytorch#195]
PS D:\ML_Data\4_2_ZQPei_deep_sort_pytorch\ZQPei_deep_sort_pytorch> python yolov3_deepsort_eval.py
D:\ML_Data\4_2_ZQPei_deep_sort_pytorch\ZQPei_deep_sort_pytorch\utils\parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
2021-02-10 17:10:54 [INFO]: start seq: MOT16-02
Traceback (most recent call last):
  File "yolov3_deepsort_eval.py", line 85, in <module>
    main(data_root=data_root,
  File "yolov3_deepsort_eval.py", line 36, in main
    with VideoTracker(cfg, args, video_path, result_filename) as vdo_trk:
TypeError: __init__() takes 4 positional arguments but 5 were given

How to fix?   thanks

**Comment by h-enes-simsek** [comment]
a good answer
https://github.com/ZQPei/deep_sort_pytorch/issues/127#issuecomment-674435481
