### ISSUE TITLE
  Training with my own data weight.pt The following error occurred

### ISSUE THREAD

**Issue by lyd959** [ZQPei/deep_sort_pytorch#202]
Traceback (most recent call last):
  File "track.py", line 5, in <module>
    from deep_sort.utils.parser import get_config
  File "/home/lyd/pyHub/Yolov5_DeepSort_Pytorch/deep_sort/utils/parser.py", line 3, in <module>
    from easydict import EasyDict as edict
ModuleNotFoundError: No module named 'easydict'
(yolo5) lyd@lyd-desktop:~/pyHub/Yolov5_DeepSort_Pytorch$ pip install -U -r requirements.txt
Requirement already satisfied: Cython in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.29.22)
Collecting Cython
  Using cached Cython-0.29.23-cp37-cp37m-manylinux1_x86_64.whl (2.0 MB)
Requirement already satisfied: matplotlib>=3.2.2 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (3.4.1)
Requirement already satisfied: numpy>=1.18.5 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.20.2)
Requirement already satisfied: opencv-python>=4.1.2 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (4.5.1.48)
Requirement already satisfied: pillow in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (8.2.0)
Collecting easydict
  Using cached easydict-1.9.tar.gz (6.4 kB)
Requirement already satisfied: PyYAML>=5.3 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (5.4.1)
Requirement already satisfied: scipy>=1.4.1 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.6.2)
Requirement already satisfied: tensorboard>=2.2 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (2.4.1)
Requirement already satisfied: torch>=1.6.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.7.1+cu101)
Collecting torch>=1.6.0
  Using cached torch-1.8.1-cp37-cp37m-manylinux1_x86_64.whl (804.1 MB)
Requirement already satisfied: torchvision>=0.7.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (0.8.2+cu101)
Collecting torchvision>=0.7.0
  Using cached torchvision-0.9.1-cp37-cp37m-manylinux1_x86_64.whl (17.4 MB)
Requirement already satisfied: tqdm>=4.41.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (4.59.0)
Collecting tqdm>=4.41.0
  Using cached tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 3)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 3)) (2.8.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (2.25.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.28.0)
Requirement already satisfied: absl-py>=0.4 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (0.12.0)
Requirement already satisfied: setuptools>=41.0.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (52.0.0.post20210125)
Requirement already satisfied: six>=1.10.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.15.0)
Requirement already satisfied: wheel>=0.26 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (0.36.2)
Requirement already satisfied: grpcio>=1.24.3 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.36.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.0.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (1.8.0)
Requirement already satisfied: protobuf>=3.6.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (3.15.6)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (0.4.4)
Requirement already satisfied: markdown>=2.6.8 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from tensorboard>=2.2->-r requirements.txt (line 11)) (3.3.4)
Requirement already satisfied: typing-extensions in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from torch>=1.6.0->-r requirements.txt (line 12)) (3.7.4.3)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (4.2.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2->-r requirements.txt (line 11)) (1.3.0)
Requirement already satisfied: importlib-metadata in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard>=2.2->-r requirements.txt (line 11)) (3.10.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard>=2.2->-r requirements.txt (line 11)) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard>=2.2->-r requirements.txt (line 11)) (4.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2->-r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: zipp>=0.5 in /home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard>=2.2->-r requirements.txt (line 11)) (3.4.1)
Building wheels for collected packages: easydict
  Building wheel for easydict (setup.py) ... done
  Created wheel for easydict: filename=easydict-1.9-py3-none-any.whl size=6350 sha256=b5bc9d260276d789f31f7c1aa3643671667cd2fd9f01ddc632fe1f52c4846f76
  Stored in directory: /home/lyd/.cache/pip/wheels/88/96/68/c2be18e7406804be2e593e1c37845f2dd20ac2ce1381ce40b0
Successfully built easydict
Installing collected packages: torch, tqdm, torchvision, easydict, Cython
  Attempting uninstall: torch
    Found existing installation: torch 1.7.1+cu101
    Uninstalling torch-1.7.1+cu101:
      Successfully uninstalled torch-1.7.1+cu101
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.59.0
    Uninstalling tqdm-4.59.0:
      Successfully uninstalled tqdm-4.59.0
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.8.2+cu101
    Uninstalling torchvision-0.8.2+cu101:
      Successfully uninstalled torchvision-0.8.2+cu101
  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.22
    Uninstalling Cython-0.29.22:
      Successfully uninstalled Cython-0.29.22
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 0.7.2 requires torch==1.7.1, but you have torch 1.8.1 which is incompatible.
Successfully installed Cython-0.29.23 easydict-1.9 torch-1.8.1 torchvision-0.9.1 tqdm-4.60.0
(yolo5) lyd@lyd-desktop:~/pyHub/Yolov5_DeepSort_Pytorch$ python3 track.py --source /media/lyd/文档/出苗率/DJI_0002.MP4
Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.4, config_deepsort='deep_sort/configs/deep_sort.yaml', device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='/media/lyd/文档/出苗率/DJI_0002.MP4', view_img=False, weights='yolov5/weights/yolov5x.pt')
/home/lyd/pyHub/Yolov5_DeepSort_Pytorch/deep_sort/utils/parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "track.py", line 238, in <module>
    detect(args)
  File "track.py", line 85, in detect
    model = torch.load(weights, map_location=device)['model'].float()  # load to FP32
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'yolov5/weights/yolov5x.pt'
(yolo5) lyd@lyd-desktop:~/pyHub/Yolov5_DeepSort_Pytorch$ python3 track.py --weights /home/lyd/pyHub/Yolov5_DeepSort_Pytorch/yolov5/weights/last.pt  --source /media/lyd/文档/出苗率/DJI_0002.MP4
Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.4, config_deepsort='deep_sort/configs/deep_sort.yaml', device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='/media/lyd/文档/出苗率/DJI_0002.MP4', view_img=False, weights='/home/lyd/pyHub/Yolov5_DeepSort_Pytorch/yolov5/weights/last.pt')
/home/lyd/pyHub/Yolov5_DeepSort_Pytorch/deep_sort/utils/parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "track.py", line 238, in <module>
    detect(args)
  File "track.py", line 85, in detect
    model = torch.load(weights, map_location=device)['model'].float()  # load to FP32
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'C3' on <module 'models.common' from './yolov5/models/common.py'>
(yolo5) lyd@lyd-desktop:~/pyHub/Yolov5_DeepSort_Pytorch$ python3 track.py --weights /home/lyd/pyHub/Yolov5_DeepSort_Pytorch/yolov5/weights/last.pt  --source /media/lyd/文档/出苗率/DJI_0002.MP4
Namespace(agnostic_nms=False, augment=False, classes=[0], conf_thres=0.4, config_deepsort='deep_sort/configs/deep_sort.yaml', device='', fourcc='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='/media/lyd/文档/出苗率/DJI_0002.MP4', view_img=False, weights='/home/lyd/pyHub/Yolov5_DeepSort_Pytorch/yolov5/weights/last.pt')
/home/lyd/pyHub/Yolov5_DeepSort_Pytorch/deep_sort/utils/parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "track.py", line 238, in <module>
    detect(args)
  File "track.py", line 85, in detect
    model = torch.load(weights, map_location=device)['model'].float()  # load to FP32
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/lyd/anaconda3/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'C3' on <module 'models.common' from './yolov5/models/common.py'>

**Comment by lyd959** [comment]
update common.py  Above 4.0 can solve

**Comment by Y-Mona** [comment]
啊兄弟，你是直接在detector.py把权重路径改成自己的的.pt嘛

**Comment by 18795908697** [comment]
> 啊兄弟，你是直接在detector.py把权重路径改成自己的的.pt嘛

兄弟, 怎么用自己训练的.pth文件来运行这个跟踪程序啊.

**Comment by yuanqiyin** [comment]
麻烦问下，你们解决了么？我改了detector.py中的路径，还有yaml文件中的路径，还利用 @Y-Mona 您的方法把权重转化了，但还是运行跟踪时检测不到目标，麻烦您可以解答一下吗？@18795908697

> 
> 
> > 啊兄弟，你是直接在detector.py把权重路径改成自己的的.pt嘛
> 
> 兄弟, 怎么用自己训练的.pth文件来运行这个跟踪程序啊.直接在detector.py里该改权重和name我试过不行,啥都不显示

**Comment by Y-Mona** [comment]
> > 啊兄弟，你是直接在detector.py把权重路径改成自己的的.pt嘛
> 
> 兄弟, 怎么用自己训练的.pth文件来运行这个跟踪程序啊.直接在detector.py里该改权重和name我试过不行,啥都不显示

还有别的文件要改，配置的.yaml什么的，可以进跟踪执行文件里看一下，需要权重的都改

**Comment by yuanqiyin** [comment]
> > > 啊兄弟，你是直接在detector.py把权重路径改成自己的的.pt嘛
> > 
> > 
> > 兄弟, 怎么用自己训练的.pth文件来运行这个跟踪程序啊.直接在detector.py里该改权重和name我试过不行,啥都不显示
> 
> 还有别的文件要改，配置的.yaml什么的，可以进跟踪执行文件里看一下，需要权重的都改

您好，我改了所有用到权重文件的地方，还是得不到跟踪的目标，用代码中带的预训练权重和对应的names文件是可以的，请问我是模型或者是哪里出现了问题么？
我暂时做了以下工作：
1.用自己的pytorch版本的yolov3训练，然后得到yolov3.pt文件；
2.利用自己训练的cfg文件进行转化，得到yolov3.weights文件；
3.替换deepsort中所有用到检测权重的地方，例如yolov3.yaml和deepsort.yaml文件；
烦请您看到回复一下，谢谢您。
