### ISSUE TITLE
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 453966

### ISSUE THREAD

**Issue by aayush1205** [ZQPei/deep_sort_pytorch#57]
Can you please help me out with this?

`Traceback (most recent call last):
  File "demo_yolo3_deepsort.py", line 95, in <module>
    with Detector(args) as det:
  File "demo_yolo3_deepsort.py", line 20, in __init__
    self.yolo3 = YOLOv3(args.yolo_cfg, args.yolo_weights, args.yolo_names, is_xywh=True, conf_thresh=args.conf_thresh, nms_thresh=args.nms_thresh)
  File "/home/aayush/new/deep_sort_pytorch/YOLOv3/detector.py", line 14, in __init__
    self.net.load_weights(weightfile)
  File "YOLOv3/darknet.py", line 353, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "YOLOv3/cfg.py", line 191, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start + num_w]).view_as(conv_model.weight.data)); start = start + num_w
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 453966`

**Comment by aayush1205** [comment]
Seems like the weight file got corrupted because of a break in the download. Closing the issue.
