### ISSUE TITLE
Error using tiny yolo in place of yolo

### ISSUE THREAD

**Issue by chinmayjog13** [ZQPei/deep_sort_pytorch#70]
```
python demo_yolo3_deepsort.py 20190821.mp4 --yolo_cfg YOLOv3/cfg/tiny-yolo.cfg --yolo_weights YOLOv3/yolov3-tiny.weights 
YOLOv3/yolov3-tiny.weights YOLOv3/cfg/tiny-yolo.cfg
Traceback (most recent call last):
  File "demo_yolo3_deepsort.py", line 99, in <module>
    with Detector(args) as det:
  File "demo_yolo3_deepsort.py", line 22, in __init__
    self.yolo3 = YOLOv3(args.yolo_cfg, args.yolo_weights, args.yolo_names, is_xywh=True, conf_thresh=args.conf_thresh, nms_thresh=args.nms_thresh, use_cuda=use_cuda)
  File "/home/chinmay/deep_sort_pytorch/YOLOv3/detector.py", line 14, in __init__
    self.net.load_weights(weightfile)
  File "YOLOv3/darknet.py", line 353, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "YOLOv3/cfg.py", line 191, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start + num_w]).view_as(conv_model.weight.data)); start = start + num_w
RuntimeError: shape '[512, 1024, 3, 3]' is invalid for input of size 2558206
```

@ZQPei  I downloaded tiny yolo weights in same folder as yolo weights, and gave appropriate arguments for cfg and weights. I get the above error, should I use the tiny yolo cfg file from pjreddie's master branch?

**Comment by ZQPei** [comment]
Hello, @chinmayjog13 .
I just add tiny yolo for detection. You can check `README.md` for more detail.
