### ISSUE TITLE
which specific version of pytorch do you use ?

### ISSUE THREAD

**Issue by basit26374** [ZQPei/deep_sort_pytorch#82]
I have installed Pytorch == 0.4.0 and torchvision == 0.2.0, but I face following error 

`<class 'AttributeError'> module 'torch' has no attribute 'clamp_min' <traceback object at 0x7f75ddac5a88>
Traceback (most recent call last):
  File "yolov3_deepsort.py", line 115, in <module>
    trk.run()
  File "yolov3_deepsort.py", line 65, in run
    bbox_xywh, cls_conf, cls_ids = self.detector(im)
  File "/home/gamelab/Abdul_Basit/deep_sort_pytorch-master/detector/YOLOv3/detector.py", line 43, in __call__
    boxes = get_all_boxes(out_boxes, self.conf_thresh, self.num_classes, use_cuda=self.use_cuda) #batch size is 1
  File "detector/YOLOv3/yolo_utils.py", line 160, in get_all_boxes
    only_objectness=only_objectness, validation=validation, use_cuda=use_cuda)
  File "detector/YOLOv3/yolo_utils.py", line 208, in get_region_boxes
    x1, y1, x2, y2 = torch.clamp_min(xs-ws/2., 0.), torch.clamp_min(ys-hs/2., 0.), torch.clamp_max(xs+ws/2., 1.), torch.clamp_max(ys+hs/2., 1.)
AttributeError: module 'torch' has no attribute 'clamp_min'`

**Comment by ZQPei** [comment]
Upgrade your pytorch to 1.x
